// Allowed table names
export enum TableName {
  USERS = 'users',
  PROJECT = 'project',
  ORG = 'org',
  PROGRAMME = 'programme',
  PROJECT_STAGE_GATE = 'project_stage_gate',
  PROJECT_ASSET = 'project_asset', 
  PROJECT_PHASE = 'project_phase',
  PROJECT_STAKEHOLDER = 'project_stake_holders', 
  STAKEHOLDER_USERS = 'stakeholder_users',
  CD_MASTERDATA = 'cd_masterdata',
  MD_FIELD = 'cd_md_field',
  MD_JOIN = 'cd_md_join',
  MD_SCREEN = 'cd_md_screen',
  MD_TABLE = 'cd_md_table',
  USER_FIELD_SELECTION = 'cd_user_field_selection',
  SELECTION_FIELD = 'cd_user_selected_fields',
  MD_STAGE_GATE = 'md_stage_gate',
  PROJECT_TASK = 'project_task',
  STAGE_GATE_CHECKLIST = 'stage_gate_checklist',
  PROJECT_ACTIVITY = 'project_activity',
  CD_ACTIVITY_LOG = 'cd_activity_log',
  PROJECT_TREE = 'project_tree',
  SCHEDULING_LINKS = 'scheduling_links',
  MD_PHASE_TYPE = 'md_phase_type',
  SITE = 'site',
  PORTFOLIO = 'portfolio',
  WORK_TYPE = 'work_type',
  WORK_TYPE_GROUP = 'work_type_group',
  MD_TASK_TYPE = 'md_task_type',
  COUNTY = 'county',
  ILN = 'iln',
  WORKSTREAM = 'workstream',
  REGION = 'region',
  STAGE_GATE_APPROVAL = 'stage_gate_approval',
  ROLES = 'cd_roles',
  COMMENT = 'comment',
  RISK = 'risks',
  USER_FAVOURITE_PROJECTS = 'user_favourite_projects',
  RULES = 'cd_rag_rules',
  UPLOADS = 'uploads',
  MIME_TYPE = 'mime_type',
  USER_SAVED_FILTERS = 'user_saved_filters',
  QUERIES = 'queries',
  MATERIAL_REQUEST = 'material_requests',
  RESOURCE_REQUEST = 'resource_requests',
  TEMPLATE_PROJECT = 'template_project',
  TEMPLATE_PHASE = 'template_phase',
  TEMPLATE_ACTIVITY = 'template_activity',
  TEMPLATE_PHASE_DEPENDENCIES = 'template_phase_dependencies',
  TASK = 'task',
  ARTEFACT = 'artefacts',
  OUTAGE_WINDOW = 'project_outage_window',
  ADJUSTMENT = 'adjustment',
  COMMITMENT = 'commitment',
  PAYMENT = 'payment',
  VARIATION = 'variation',
  FORECAST = 'forecast',
  BUDGET = 'budget',
  RISK_ASSESSMENT = 'risk_assessment',
  RAG_RULES = 'cd_rag_rules',
  RISK_CAUSE = 'risk_causes',
  RISK_MITIGATION = 'risk_mitigations',
  COMMITMENT_LINE_ITEM = 'commitment_line_item',
  NETWORK_ZONE = 'uk_network_zone',
  MEETING = 'meeting',
  MEETING_PROJETCS = 'meeting_projects',
  MEETING_ATTENDEES = 'meeting_attendees',
  MEETING_EXTERNAL_ATTENDEES = 'meeting_external_attendees',
  CONTRACTOR = 'contractor',
  JEOPARDY = 'jeopardy',
  JEOPARDY_TASK = 'jeopardy_task',
  CRON_JOB_FAILURE = 'cron_job_failures',
  REMINDER = 'reminder',
  JEOPARDY_ACKNOWLEDGEMENT = 'jeopardy_acknowledgement',
  NOTIFICATIONS_LOG = 'notifications_log',
  FILTER_MAP = 'filter_map',
  IMPORT_CONFIG = 'import_field_config',
  BATCH_HEADER = 'batch_header',
  BATCH_DETAIL = 'batch_detail',
  IMPORT_TEMPLATE = 'import_template',
  AREA = 'area',
  REPORT = 'report',
  REPORT_COLUMN_MAPPING = 'report_column_mapping',
  REPORT_FILTER = 'report_filter',
  REPORT_TEMPLATE = 'report_templates',
  TEMPLATE_COLUMN_MAPPING = 'template_column_mapping',
  EXPORT_LOG = 'export_log',
  TEMPLATE_STAKEHOLDER = 'template_stakeholders',
  BUSINESS_ROLES = 'cd_business_roles',
  PROJECT_SNAPSHOT = 'project_snapshot',
  PROJECT_ASSET_SNAPSHOT = 'project_asset_snapshot',
  PROJECT_STAKE_HOLDERS_SNAPSHOT = 'project_stake_holders_snapshot',
  ACTIVITY_SNAPSHOT = 'activity_snapshot',
  ARTEFACTS_SNAPSHOT = 'artefacts_snapshot',
  JEOPARDY_SNAPSHOT = 'jeopardy_snapshot',
  MEETING_SNAPSHOT = 'meeting_snapshot',
  QUERY_SNAPSHOT = 'query_snapshot',
  RISKS_SNAPSHOT = 'risks_snapshot',
  TASK_SNAPSHOT = 'task_snapshot',
  COMMITMENT_SNAPSHOT = 'commitment_snapshot',
  COMMITMENT_LINE_ITEM_SNAPSHOT = 'commitment_line_item_snapshot',
  PAYMENT_SNAPSHOT = 'payment_snapshot',
  ADJUSTMENT_SNAPSHOT = 'adjustment_snapshot',
  FORECAST_SNAPSHOT = 'forecast_snapshot',
  VARIATION_SNAPSHOT = 'variation_snapshot',
  MATERIAL_REQUEST_SNAPSHOT = 'material_request_snapshot',
  BUDGET_SNAPSHOT = 'budget_snapshot',
  RESOURCE_REQUEST_SNAPSHOT = 'resource_requests_snapshot',
  STAGE_GATE_SNAPSHOT = 'stage_gate_snapshot',
  STAGE_GATE_APPROVAL_SNAPSHOT = 'stage_gate_approval_snapshot',
  STAGE_GATE_CHECKLIST_SNAPSHOT = 'stage_gate_checklist_snapshot',
  PORTFOLIO_SNAPSHOT = 'portfolio_snapshot',
  STAGEGATE_COMMENT_SNAPSHOT = 'stagegate_comment_snapshot',
  PHASE_SNAPSHOT = 'phase_snapshot',
  PROJECT_SNAPSHOT_NEW = 'project_snapshot_new',
  TEMPLATE_CHECKLIST = 'template_checklist',
  TEMPLATE_DOCUMENT = 'template_document',
  EVENT = 'event',
  EVENT_OUTBOX = 'event_outbox',
  TEMPLATE_APPROVALS = 'template_approvals_new',
  EVENT_PROCESSING_LOG = 'event_processing_log',
  NOTIFICATIONS = 'notifications',
  NOTIFICATION_TEMPLATES = 'notification_templates',
  ACTIVITY_TASKS = 'activity_task',
  TEMPLATE_ACTIVITY_TODO = 'template_activity_todo',
}

// Allowed fields for each table
export const ALLOWED_FIELDS: Record<TableName, readonly string[]> = {
  [TableName.CONTRACTOR]: ['id','display_name','code','is_active','created_by','created_date','updated_by','updated_date',] as const,
  [TableName.NETWORK_ZONE]: ['asset_id', 'type', 'geo_point_2d', 'geo_location', 'zone_name', 'updated_date', 'updated_by'] as const,
  [TableName.ARTEFACT]: ['id','checklist_id','artefact_ref','stage_gate_id','title','category','sub_category','description','assigned_to','status','compliance','required_date','created_by','created_at','updated_by','updated_at','file_version'] as const,
  [TableName.IMPORT_TEMPLATE]: ['id', 'template_name', 's3_bucket_name', 's3_path', 'template_type', 'content_type', 'created_by','created_date'] as const,
  [TableName.RULES]: ['rule_json', 'created_at', 'updated_at', 'id', 'is_active', 'rule_name', 'entity_type'] as const,
  [TableName.RISK_ASSESSMENT]: ['id','imp_prob_score', 'risk_id', 'title', 'description', 'status', 'impact', 'impact_score', 'probability_score', 'created_at', 'created_by', 'updated_at', 'updated_by', 'probability' ] as const,
  [TableName.MIME_TYPE]: ['id', 'created_time', 'updated_time', 's3_path', 'created_by', 'updated_by', 'mime_type', 'file_ext'] as const,
  [TableName.UPLOADS]: ['file_id','expiry_date','parent_id','parent_id','file_size', 'created_date', 'updated_date', 'object_id', 'file_export', 'batch_id', 'mime_type', 's3_file_location', 's3_bucket_name', 's3_path', 'owner_reference', 'created_by', 'source_type', 'updated_by', 'file_uuid', 'file_reference', 'file_type', 'file_name', 'file_extension', 'thumbnail_s3_path'] as const,
  [TableName.COMMENT]: ['comment_id','status_date', 'created_date', 'updated_date', 'parent_id', 'user_name', 'comment_topic', 'created_by', 'updated_by', 'object_id', 'object_type', 'comment_text'] as const,
  [TableName.STAGE_GATE_APPROVAL]: ['id','notes','work_stream_id','updated_by','updated_at','created_date','user_id','is_decision_gate','stage_gate_id','created_by','status','tag'] as const,
  [TableName.MD_TASK_TYPE]: ['id', 'name', 'description', 'activity_type_id', 'sequence_order', 'is_active', 'created_date', 'updated_at', 'created_by', 'updated_by'] as const,
  [TableName.WORK_TYPE_GROUP]: ['id', 'code', 'description', 'is_active', 'created_date', 'updated_at', 'created_by', 'updated_by'] as const,
  [TableName.WORK_TYPE]: ['id', 'code', 'description', 'is_active', 'created_date', 'updated_at', 'created_by', 'updated_by'] as const,
  [TableName.PORTFOLIO]: ['id', 'is_active', 'created_date', 'updated_at', 'created_by', 'updated_by', 'programme_id', 'actual_spend', 'start_date', 'end_date', 'budget_value', 'portfolio_reference', 'portfolio_name', 'description', 'portfolio_status'] as const,
  [TableName.SITE]: ['id', 'is_active', 'created_date', 'updated_at', 'created_by', 'description', 'code', 'updated_by'] as const,
  [TableName.USERS]: ['user_id', 'cognito_id', 'email', 'first_name', 'last_name', 'created_at', 'created_by', 'updated_at', 'updated_by', 'preferred_username', 'layout_id'] as const,
  [TableName.PROJECT]: ['id','authorized_budget','programme_id','portfolio_id','org_id','region_id','workstream_id','project_reference','title','description','functional_location','work_type_id','wbs_code_id','iln_number_id','owner_id','site_name','start_date','end_date','commission_date','close_out_date','project_status','is_active','created_by','created_date','updated_by','updated_at','code'] as const,
  [TableName.ORG]: ['id','description','code','is_active','created_by','created_date','updated_by','updated_at'] as const,
  [TableName.PROGRAMME]: ['id','project_id','stage_gate_id','name','description','status','criteria_met_percentage','approved_by','approved_date','rejected_reason','bypass_reason','bypass_approved_by','position_after_phase_id','position_after_activity_id','position_after_task_id','effective_from','is_active','sequence_order','can_proceed','created_by','created_date','updated_by','updated_at'] as const,
  [TableName.PROJECT_STAGE_GATE]: ['id','project_id','stage_gate_id','name','description','status','criteria_met_percentage','approved_by','approved_date','rejected_reason','bypass_reason','bypass_approved_by','position_after_phase_id','position_after_activity_id','position_after_task_id','effective_from','is_active','sequence_order','can_proceed','created_by','created_date','updated_by','updated_at'] as const,
  [TableName.PROJECT_ASSET]: ['id', 'project_id', 'name', 'code', 'description', 'category', 'asset_value', 'asset_budget', 'asset_type', 'work_type_group_id', 'work_type', 'iln_id', 'iln', 'functional_location', 'is_active', 'approval_required', 'created_by', 'created_date', 'updated_by', 'updated_at', 'asset_category', 'narms_value', 'programme_id', 'sap_hierarchy'] as const,
  [TableName.PROJECT_PHASE]: ['id', 'project_id', 'phase_type_id', 'name', 'description', 'planned_start_date', 'planned_end_date', 'actual_start_date', 'actual_end_date', 'status', 'sequence_order', 'budget_allocated', 'can_start', 'created_by', 'created_date', 'updated_by', 'updated_at', 'principle_design_engineer', 'successor_activity_gate', 'prev_id', 'next_id'] as const,
  [TableName.PROJECT_STAKEHOLDER]: ['id', 'project_id', 'user_id', 'role_id', 'description', 'is_active', 'created_by', 'created_date', 'updated_by', 'updated_at'] as const,
  [TableName.STAKEHOLDER_USERS]: ['id', 'first_name', 'last_name', 'full_name', 'email', 'role', 'role_access', 'phone_number', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.MD_SCREEN]: ['id', 'base_table_id', 'is_active', 'created_date', 'output_type', 'screen_name', 'display_name', 'description'] as const,
  [TableName.MD_TABLE]: ['id', 'is_active', 'created_date', 'description', 'display_name', 'table_name', 'table_alias'] as const,
  [TableName.USER_FIELD_SELECTION]: ['updated_at', 'user_id', 'screen_id', 'id', 'is_default', 'created_at', 'selection_name'] as const,
  [TableName.SELECTION_FIELD]: ['id', 'selection_id', 'field_id', 'display_order', 'column_width', 'is_visible', 'created_at', 'group_id', 'is_export', 'is_editable', 'layout_position', 'display_name'] as const,
  [TableName.MD_JOIN]: ['id','from_table_id','to_table_id','is_active','created_date','to_field','join_type','from_field'] as const,
  [TableName.MD_FIELD]: ['is_import','table_id','is_sortable','is_active','sort_order','created_date','is_derived','is_show','id','is_filterable','field_name','field_alias','display_name','data_type','description','db_expression','domain'] as const,
  [TableName.CD_MASTERDATA]: ['id', 'name', 'created_at','created_by','updated_at','updated_by','update_date','display_order','is_active','is_deleted','is_disable','create_date','masterdata_id','parent_key','abbrevation','action','color','domain','key','value','display_text','description','helper_text'] as const,
  [TableName.MD_STAGE_GATE]: ['id', 'name', 'description', 'sequence_order', 'gate_type', 'approval_required', 'is_active', 'created_by', 'created_date', 'updated_by', 'updated_at'] as const,
  [TableName.PROJECT_ACTIVITY]: ['project_id','project_phase_id','activity_type_id','actual_end_date','sequence_order','progress_percentage','assigned_to','can_start','created_date','updated_at','role_id','id','planned_start_date','planned_end_date','actual_start_date','name','description','owner_role','activity_ref','created_by','phase_ref','status','updated_by','project_ref'] as const,
  [TableName.PROJECT_TASK]: ['id','project_activity_id','task_type_id','estimated_hours','actual_hours','assigned_to','progress_percentage','can_start','created_date','updated_at','role_id','due_date','planned_start_date','planned_end_date','actual_start_date','actual_end_date','name','description','role','updated_by','task_ref','activity_ref','status','priority','created_by'] as const,
  [TableName.CD_ACTIVITY_LOG]: ['activity_log_id', 'topic', 'event', 'object_id', 'object_type', 'object_ref', 'comment_text', 'is_deleted', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.PROJECT_TREE]: ['id', 'activity_task','contractor_id','project_id', 'parent_id', 'can_start', 'budget_allocated', 'user_id', 'role_id', 'sequence_order', 'stage_gate_id', 'phase_type_id', 'planned_start_date', 'planned_end_date', 'actual_start_date', 'actual_end_date', 'progress_percentage', 'name', 'category', 'description', 'status', 'color', 'type', 'assigned_to', 'created_at', 'updated_at', 'created_by', 'updated_by'] as const,
  [TableName.SCHEDULING_LINKS]: ['id', 'project_id', 'source_id', 'target_id', 'dependency_type', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.MD_PHASE_TYPE]: ['id', 'name', 'description', 'sequence_order', 'is_active', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.COUNTY]: ['id', 'description', 'code', 'is_active', 'created_by', 'created_date', 'updated_by', 'updated_at'] as const,
  [TableName.ILN]: ['id', 'code', 'description', 'hcode', 'created_by', 'created_date', 'updated_by', 'updated_at'] as const,
  [TableName.WORKSTREAM]: ['id', 'description', 'code', 'is_active', 'created_by', 'created_date', 'updated_by', 'updated_at'] as const,
  [TableName.ROLES]: ['id', 'name', 'key', 'system_role', 'layout', 'created_at', 'updated_at', 'created_by', 'updated_by'] as const,
  [TableName.REGION]: ['id', 'description', 'code', 'is_active', 'created_by', 'created_date', 'updated_by', 'updated_at'] as const,
  [TableName.STAGE_GATE_CHECKLIST]: ['id', 'stage_gate_id', 'name', 'user_id', 'is_evidence_required', 'is_required', 'status', 'due_date', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.RISK]: ['risk_id', 'risk_ref','project_ref','project_id','title','risk_description','category','raised_by','status','review_date','cause_id','cause_title','cause_status','cause_description','impact_title','impact_status','impact_description','impact','impact_score','probability','probability_score','mitigation_impact','mitigation_title','mitigation_description','mitigation_owner','residual_impact','residual_impact_score','residual_probability','residual_probability_score','created_at','created_by','updated_at','updated_by','object_type','risk_details','priority'] as const,
  [TableName.USER_FAVOURITE_PROJECTS]: ['id', 'user_id', 'project_id', 'created_at', 'created_by'] as const,
  [TableName.USER_SAVED_FILTERS]: ['id', 'user_id', 'tab_name', 'filter_name', 'filter_json', 'created_by', 'updated_by', 'created_at', 'updated_at'] as const,
  [TableName.QUERIES]: ['id', 'project_id', 'portfolio_id', 'programme_id', 'project_tree_id', 'query_reference_number', 'title', 'description', 'category', 'priority', 'status', 'raised_by', 'submitted_date', 'user_id', 'sla_date', 'due_date', 'created_at', 'created_by', 'updated_at', 'updated_by', 'project_phase'] as const,
  [TableName.MATERIAL_REQUEST]: ['id', 'material_ref', 'project_id', 'phase_id', 'activity_id', 'type', 'description', 'quantity', 'date_order_placed', 'est_delivery_date', 'supplier', 'point_of_contact_info', 'owner_of_request', 'status', 'required_date', 'last_updated_comments', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.RESOURCE_REQUEST]: ['id', 'resource_ref', 'project_id', 'phase_id', 'activity_id', 'resource_type', 'description', 'duration', 'required_date', 'requested_date', 'confirmed_date', 'status', 'resource_supplier', 'comments', 'owner_of_request', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.TEMPLATE_PROJECT]: ['id','workstream_id','work_type_group_id','work_type_id','template_name','description','is_active','created_by','created_date','updated_by','updated_at'] as const,
  [TableName.TEMPLATE_PHASE]: ['id','project_template_id','phase_type_id','name','description','sequence_order','updated_by','updated_at','created_by','created_date'] as const,
  [TableName.TEMPLATE_ACTIVITY]: ['id','template_phase_id','activity_type_id','name','description','category','sequence_order','updated_by','updated_at','created_by','created_date'] as const,
  [TableName.TEMPLATE_PHASE_DEPENDENCIES]: ['id','is_active','project_template_id','source_template_phase_id','target_template_phase_id','dependency_type','created_by','created_at','updated_by','updated_at'] as const,
  [TableName.TASK]: ['task_id','due_date','object_id','role_id','user_id','tag','object_type','task_name','assigned_to','source_entity','status','is_evidence_required','is_required','description','tags','priority','target_date','created_at','created_by','updated_at','updated_by'] as const,
  [TableName.ADJUSTMENT]: ['id', 'from_budget', 'to_budget', 'amount', 'reason', 'created_by', 'created_at', 'updated_by', 'updated_at'] as const,
  [TableName.COMMITMENT]: ['contract_id', 'budget_id', 'project_id', 'title', 'supplier', 'status', 'iln', 'po_reference', 'original_value', 'current_value', 'variation_value', 'invoiced', 'paid', 'accrued', 'retention_held', 'progress_percent', 'remaining', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.PAYMENT]: ['id', 'contract_id', 'project_id', 'payment_details', 'type', 'status', 'supplier', 'amount', 'previous_payment', 'amount_paid', 'percent_complete', 'date_submitted', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.VARIATION]: ['id', 'contract_id', 'budget_id', 'project_id', 'variation_details', 'category', 'time_changes', 'supplier', 'variance_amount', 'status', 'date_raised', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.FORECAST]: ['id', 'project_id', 'budget_id', 'forecast_type', 'period', 'forecast_value', 'cumulative_forecast', 'variance_to_baseline', 'last_updated_by', 'last_updated_date', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.BUDGET]: ['id', 'project_id', 'name', 'phase_activity', 'status', 'cbs_code', 'wbs_code', 'baseline', 'adjustment', 'committed', 'actual', 'forecast', 'variance', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.OUTAGE_WINDOW]: ['id', 'project_id', 'outage_start_date', 'outage_end_date', 'status', 'created_by', 'created_at', 'updated_by', 'updated_at'] as const,
  [TableName.RISK_CAUSE]: ['id','risk_id','title','description','status','created_at','created_by','updated_at','updated_by'] as const,
  [TableName.RISK_MITIGATION]: ['id','imp_prob_score','risk_id','impact','title','description','owner','residual_impact_score','residual_probability_score','created_at','created_by','updated_at','updated_by','residual_probability','residual_impact','user_id'] as const,
  [TableName.COMMITMENT_LINE_ITEM]: ['id', 'commitment_id', 'budget_id', 'description', 'created_by', 'created_at', 'updated_by', 'updated_at', 'amount'] as const,
  [TableName.MEETING]: ['id', 'meeting_reference', 'title', 'start_date', 'start_time', 'end_time', 'end_date', 'location', 'category', 'agenda', 'additional_points', 'attendees', 'projects', 'created_by', 'created_date', 'updated_by', 'updated_date', 'recurring_type', 'is_recurring', 'parent_id'] as const,
  [TableName.MEETING_PROJETCS]: ['id', 'meeting_id', 'project_ref', 'created_by', 'created_date'] as const,
  [TableName.MEETING_ATTENDEES]: ['id', 'meeting_id', 'user_id', 'attended', 'created_by', 'created_at'] as const,
  [TableName.MEETING_EXTERNAL_ATTENDEES]: ['id', 'meeting_id', 'full_name', 'email', 'attended', 'created_by', 'created_at'] as const,
  [TableName.JEOPARDY]: ['id', 'jeopardy_ref', 'task_id', 'jeopardy_task', 'topic', 'category', 'sub_category', 'headline', 'details', 'severity', 'status', 'due_date', 'reported_on', 'closed_date', 'assigned_to', 'accountable_person', 'role', 'cmd_group_name', 'remainder_flag', 'closure_reason', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.JEOPARDY_TASK]: ['task_id', 'group_name', 'task_text', 'created_date', 'created_by', 'updated_date', 'updated_by'] as const,
  [TableName.CRON_JOB_FAILURE]: ['id', 'job_name', 'job_type', 'reference_type', 'reference_id', 'payload', 'failure_code', 'error_message', 'error_stack', 'created_at'] as const,
  [TableName.REMINDER]: ['id', 'reminder_title', 'jeopardy_id', 'reminder_ref', 'reminder_date', 'is_completed', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.JEOPARDY_ACKNOWLEDGEMENT]: ['id', 'user_id', 'jeopardy_id', 'acknowledged_by', 'acknowledged_at', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const, 
  [TableName.NOTIFICATIONS_LOG]: ['id', 'reference_type', 'reference', 'channel', 'recipient', 'successful', 'content', 'requesting_cognito_id', 'requesting_user_email', 'message_id', 'created_at', 'created_by', 'updated_at', 'updated_by'] as const,
  [TableName.FILTER_MAP]: ['filter_id', 'org_id', 'org_name', 'region_id', 'region_name', 'workstream_id', 'workstream_name', 'work_type_id', 'work_type_name', 'programme_id', 'programme_name', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.IMPORT_CONFIG]: ['id','client_id','template_type','field_name','display_name','data_type','is_required','validation_rules','client_specific_rules','created_by','created_date','updated_by','updated_at','md_domain'] as const,
  [TableName.BATCH_HEADER]: ['id','batch_id','client_id','template_type','file_name','s3_key','total_rows','processed_rows','successful_rows','failed_rows','warning_count','status','started_at','completed_at','metadata','created_by','created_date','updated_by','updated_date'] as const,
  [TableName.AREA]: ['id','description','code','is_active','created_by','created_date','updated_by','updated_at'] as const,
  [TableName.BATCH_DETAIL]: ['id','batch_header_id','row_number','original_data','processed_data','status','error_count','error_message','processed_date','created_by','created_date','updated_by','updated_date','success_message','object_reference','object_id'] as const,
  [TableName.REPORT]: ['report_id', 'report_name', 'report_type', 'display_name', 'object_value', 'object_type', 'group_by', 'email_to', 'email_cc', 'email_from', 'column_names', 'report_query', 'date_mapping', 'created_by', 'create_date', 'updated_by', 'update_date', 'is_active'] as const,
  [TableName.REPORT_COLUMN_MAPPING]: ['report_column_id', 'report_id', 'object_type', 'join_name', 'column_name', 'native_field', 'data_type', 'enum_name', 'master_filter_type', 'column_display_name', 'native_query', 'is_show', 'display_order', 'entity', 'join_type', 'join', 'sub_join', 'create_date', 'created_by', 'update_date', 'updated_by'] as const,
  [TableName.REPORT_FILTER]: ['filter_id', 'report_id', 'report_name', 'field_property', 'join_type', 'enum_path', 'filter_name', 'format', 'is_fixed', 'data_type', 'filter_type', 'filter_key', 'enum_value', 'master_data_source', 'domain', 'is_master_data', 'display_name', 'field_data', 'display_order', 'fixed_value', 'is_show', 'except_user', 'create_date', 'created_by', 'update_date', 'updated_by'] as const,
  [TableName.REPORT_TEMPLATE]: ['template_id', 'report_id', 'user_id', 'template_name', 'template_type', 'object_type', 'object_value', 'filter', 'global_filter', 'is_active', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.TEMPLATE_COLUMN_MAPPING]: ['id', 'template_id', 'column_id', 'display_order', 'created_by', 'created_date'] as const,
  [TableName.BUSINESS_ROLES]: ['id','business_role','description','created_by','updated_by','created_at','updated_at'] as const,
  [TableName.TEMPLATE_STAKEHOLDER]: ['id','workstream','workstream_id','region','region_id','work_type_group','work_type_group_id','work_type','work_type_id','business_role','role_id','user_name','user_id'] as const,
  [TableName.EXPORT_LOG]: ['export_id', 'export_name', 'no_of_records', 'username', 'file_name', 'object_ref_id', 'file_type', 'file_size', 'status', 'is_deleted', 'created_by', 'create_date', 'updated_by', 'update_date'] as const,
  [TableName.PROJECT_SNAPSHOT]: ['id', 'project_id', 'project', 'snapshot_at'] as const,
  [TableName.PROJECT_SNAPSHOT_NEW]: ['id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'project', 'snapshot_at'] as const,
  [TableName.PROJECT_STAKE_HOLDERS_SNAPSHOT]: ['id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'stakeholders', 'snapshot_at'] as const,
  [TableName.PHASE_SNAPSHOT]: ['id', 'phase_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'phases', 'snapshot_at'] as const,
  [TableName.PROJECT_ASSET_SNAPSHOT]: ['id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'project_assets', 'snapshot_at'] as const,
  [TableName.ACTIVITY_SNAPSHOT]: ['id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'activities', 'snapshot_at'] as const,
  [TableName.STAGE_GATE_SNAPSHOT]: ['id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'stage_gates', 'snapshot_at'] as const,
  [TableName.STAGE_GATE_APPROVAL_SNAPSHOT]: ['id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'approvals', 'snapshot_at'] as const,
  [TableName.STAGE_GATE_CHECKLIST_SNAPSHOT]: ['id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'checklists', 'snapshot_at'] as const,
  [TableName.ARTEFACTS_SNAPSHOT]: ['id', 'artefact_id', 'project_id', 'programme_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'artefact', 'snapshot_at'] as const,
  [TableName.JEOPARDY_SNAPSHOT]: ['id', 'jeopardy_id', 'task_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'jeopardy', 'snapshot_at'] as const,
  [TableName.MEETING_SNAPSHOT]: ['id', 'meeting_id', 'project_id', 'project_title', 'programme_id', 'programme', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'meeting', 'snapshot_at'] as const,
  [TableName.QUERY_SNAPSHOT]: ['id', 'query_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'query', 'snapshot_at'] as const,
  [TableName.RISKS_SNAPSHOT]: ['id', 'risk_id', 'project_id', 'project_tree_id', 'programme_id', 'portfolio_id', 'risk', 'snapshot_at'] as const,
  [TableName.TASK_SNAPSHOT]: ['id', 'task_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'task', 'snapshot_at'] as const,
  [TableName.COMMITMENT_SNAPSHOT]: ['id', 'commitment_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'commitment', 'snapshot_at'] as const,
  [TableName.COMMITMENT_LINE_ITEM_SNAPSHOT]: ['id', 'line_item_id', 'commitment_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'line_item_data', 'snapshot_at'] as const,
  [TableName.PAYMENT_SNAPSHOT]: ['id', 'payment_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'payment', 'snapshot_at'] as const,
  [TableName.ADJUSTMENT_SNAPSHOT]: ['id', 'adjustment_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'adjustment', 'snapshot_at'] as const,
  [TableName.FORECAST_SNAPSHOT]: ['id', 'forecast_id', 'project_id', 'programme_id', 'portfolio_id', 'budget_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'forecast', 'snapshot_at'] as const,
  [TableName.VARIATION_SNAPSHOT]: ['id', 'variation_id', 'project_id', 'programme_id', 'portfolio_id', 'contractor_id', 'budget_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'variation', 'snapshot_at'] as const,
  [TableName.MATERIAL_REQUEST_SNAPSHOT]: ['id', 'material_request_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'material_data', 'snapshot_at'] as const,
  [TableName.BUDGET_SNAPSHOT]: ['id', 'budget_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'budget', 'snapshot_at'] as const,
  [TableName.RESOURCE_REQUEST_SNAPSHOT]: ['id', 'resource_request_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'resource_data', 'snapshot_at'] as const,
  [TableName.PORTFOLIO_SNAPSHOT]: ['id', 'portfolio_id', 'programme_id', 'portfolio', 'snapshot_at'] as const,
  [TableName.STAGEGATE_COMMENT_SNAPSHOT]: ['id', 'comment_id', 'object_id', 'project_id', 'programme_id', 'portfolio_id', 'region_id', 'org_id', 'workstream_id', 'work_type_id', 'comment', 'snapshot_at'] as const,
  [TableName.TEMPLATE_CHECKLIST]: ['id', 'workstream_id', 'workstream', 'worktype_group_id', 'worktype_group', 'worktype_id', 'worktype', 'stage_gate_id', 'stage_gate', 'checklist_title', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.TEMPLATE_DOCUMENT]: ['id', 'workstream_id', 'workstream', 'worktype_group_id', 'worktype_group', 'worktype_id', 'worktype', 'stage_gate_id', 'stage_gate', 'artefact_title', 'artefact_description', 'artefact_category', 'artefact_sub_category', 'created_by', 'created_date', 'updated_by', 'updated_date'] as const,
  [TableName.EVENT]: ['id', 'client_id', 'event_name', 'event_description', 'created_by', 'created_at', 'is_active'] as const,
  [TableName.TEMPLATE_APPROVALS]: ['id','stage_gate','stage_gate_id','is_decision_maker','template_project_id','stakeholder_id','created_by','created_at','updated_by','updated_at'] as const,
  [TableName.EVENT_OUTBOX]: ['event_id', 'event_type', 'entity_type', 'entity_id', 'payload', 'target_system', 'status', 'occurred_at', 'created_at', 'event_type_id', 'retry_count', 'updated_at'] as const,
  [TableName.NOTIFICATION_TEMPLATES]: ['id','relative_url','type','title','title_description','object_type','created_date','created_by','updated_date','updated_by'] as const,
  [TableName.ACTIVITY_TASKS]: ['id', 'template_activity_id', 'description', 'created_date', 'created_by', 'updated_date', 'updated_by'] as const,
  [TableName.TEMPLATE_ACTIVITY_TODO]: ['id', 'template_project_id', 'activity_id', 'to_do_description', 'created_date', 'created_by', 'updated_date', 'updated_by'] as const,
  [TableName.NOTIFICATIONS]: ['id','user_id','object_id','object_type','active_from','read','date_read','title','title_description','relative_url','type','created_at','created_by','updated_at','updated_by','mobile_url','project_id','programme_id','portfolio_id','is_owner'] as const,
  [TableName.EVENT_PROCESSING_LOG]: ['id', 'source_system', 'event_type', 'payload', 'processing_status', 'error_message', 'processed_at'] as const,
};

// Extract allowed fields for a given table
export type AllowedFields<T extends TableName> = typeof ALLOWED_FIELDS[T][number];

// SQL to generate all columns in a table
// ---
// SELECT string_agg(quote_literal(column_name), ', ') AS column_list
// FROM information_schema.columns
// WHERE table_name = 'cr_note' AND table_schema = 'control_room';
